services:
  
  dynaarm-jazzy-dev-base:
    image: ghcr.io/duatic/dev-workspace/dynaarm-jazzy:latest
    container_name: dynaarm-jazzy-dev
    environment:
      DISPLAY: ${DISPLAY:-:0}
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1 # corresponds to 'unlimited'
      memlock: 8428281856    
    stdin_open: true
    tty: true    
    volumes:
      - ../src:/ros2_ws/src            
      - /etc/security/limits.conf:/etc/security/limits.conf
      - /tmp/.X11-unix:/tmp/.X11-unix      
      - duatic-root-cache:/root/.cache      
      