name: Build Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allows manual run from GitHub UI

jobs:
  build-dev-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx (for advanced builds, optional)
        uses: docker/setup-buildx-action@v3

      - name: Make scripts executable
        run: chmod +x ./scripts/*.sh

      - name: Run clone_repos.sh
        run: ./scripts/clone_repos.sh

      - name: Build Docker image using build_image.sh
        run: ./scripts/build_image.sh
